// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVQrPi3BP07_rcXy3nVDKuUSKA00eP9P0',
    appId: '1:408723488319:web:0a30aff2cb574e803ac28a',
    messagingSenderId: '408723488319',
    projectId: 'flutter-app-8f646',
    authDomain: 'flutter-app-8f646.firebaseapp.com',
    storageBucket: 'flutter-app-8f646.appspot.com',
    measurementId: 'G-L3P00N6DZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAJ94NcmDl7Tam_YAERclu3X9LAe6sS2o',
    appId: '1:408723488319:android:d0879ac86c7b1a1b3ac28a',
    messagingSenderId: '408723488319',
    projectId: 'flutter-app-8f646',
    storageBucket: 'flutter-app-8f646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_fMBcHSFDbBaKQEmS4sut7f6dkzUqBo',
    appId: '1:408723488319:ios:25919f8dcd777ea23ac28a',
    messagingSenderId: '408723488319',
    projectId: 'flutter-app-8f646',
    storageBucket: 'flutter-app-8f646.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI_fMBcHSFDbBaKQEmS4sut7f6dkzUqBo',
    appId: '1:408723488319:ios:87e55836419092303ac28a',
    messagingSenderId: '408723488319',
    projectId: 'flutter-app-8f646',
    storageBucket: 'flutter-app-8f646.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
